### ISSUE TITLE
wasm32 + wgpu: `CreationContext.wgpu_render_state` is `None`

### ISSUE THREAD

**Issue by juliusmh** [emilk/eframe_template#182]
I'm failing to get a valid `wgpu_render_state` from `CreationContext` when compiling for `wasm32`. The same code works in a native build. I'm new to rust/egui/wgpu!

I'm following the files in this repository:

```rust
// main.rs
#[cfg(target_arch = "wasm32")]
fn main() {
    use eframe::wasm_bindgen::JsCast as _;
    eframe::WebLogger::init(log::LevelFilter::Debug).ok();
    let web_options = eframe::WebOptions::default();
    wasm_bindgen_futures::spawn_local(async {
        let document = ...
        let canvas = ...
        let start_result = eframe::WebRunner::new()
            .start(
                canvas,
                web_options,
                Box::new(|cc| Ok(Box::new(spectral::App::new(cc)))),
            )
            .await;

        // ...

```

and in the constructor:

```rust
// tracer.rs
let render_state = cc.wgpu_render_state
  .as_ref()
  .expect("Should have a WGPU render state")
  .clone();
// ...
```

but 

```
127.0.0.1/:122 The `integrity` attribute is currently ignored for preload destinations that do not support subresource integrity. See https://crbug.com/981419 for more informationUnderstand this warningAI

127.0.0.1/:125 Unchecked runtime.lastError: The message port closed before a response was received.Understand this errorAI

spectral.js:790 panicked at src/tracer.rs:36:14:
Should have a WGPU render state

Stack:

Error
    at imports.wbg.__wbg_new_48e28ac811401d8f (http://127.0.0.1:8080/spectral.js:1530:21)
    at spectral-b1d27bf2fd4ae061.wasm.__wbg_new_48e28ac811401d8f externref shim (http://127.0.0.1:8080/spectral_bg.wasm:wasm-function[37010]:0xc20629)
    at spectral-b1d27bf2fd4ae061.wasm.eframe::web::panic_handler::Error::new::h2f1c9eb4d9e5faba (http://127.0.0.1:8080/spectral_bg.wasm:wasm-function[24433]:0xb64d38)
```

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "spectral"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
env_logger = { version = "0.11.6" }
bytemuck = { version = "1.21.0", features = ["derive"] }
nalgebra = { version = "0.33.2" }
nalgebra-glm = { version = "0.19.0", features = ["convert-bytemuck"] }
eframe = { version = "0.30.0", features = ["wgpu", "persistence", "default_fonts"]}
tobj = { version = "4.0.2" }
bvh = { version="0.10.0" }

tera = "1.20.0"
rust-embed = "8.5.0"
lazy_static = "1.5.0"
log = "0.4.22"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.49"
web-sys = "0.3.76"
```

</details>
