### ISSUE TITLE
Incremental compilation fails because of Rust analyzer invalidating build cache 

### ISSUE THREAD

**Issue by coderedart** [emilk/eframe_template#93]
The problem is tracked at https://github.com/rust-lang/rust-analyzer/issues/12688

This finally explains why we didn't have this issue when we added trunk. The issue only started popping up after https://github.com/emilk/eframe_template/pull/81 where we added unstable web apis flag 

```toml
[build]
rustflags = ["--cfg=web_sys_unstable_apis"] 
```

The workaround mentioned is to use
```toml
[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
```

you can remove the `[build]` section if you use rust analyzer vscode settings like me and comment out wasm when you need to work on a wasm project.
```json
  // "rust-analyzer.cargo.target": "x86_64-pc-windows-gnu",
  // "rust-analyzer.cargo.target": "wasm32-unknown-unknown",
```
